# Generated by Django 4.0.5 on 2022-06-18 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0002_alter_ability_name_alter_elementtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='hidden_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_ability', to='dex.ability'),
        ),
    ]
