# Generated by Django 4.0.5 on 2022-07-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0006_pokemon_max_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=50)),
                ('move_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovesByLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_level', models.IntegerField()),
                ('learned_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.moves')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves_by_level',
            field=models.ManyToManyField(to='dex.movesbylevel'),
        ),
    ]
