# Generated by Django 4.0.5 on 2022-07-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0010_move_accuracy_move_category_move_element_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
