# Generated by Django 4.0.5 on 2022-07-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0011_alter_move_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='accuracy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='power',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='move',
            name='pp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='move',
            name='probability',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
