# Generated by Django 4.0.5 on 2022-06-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='elementtype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
