# Generated by Django 4.0.5 on 2022-07-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0005_alter_pokemon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='max_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
