# Generated by Django 4.0.5 on 2022-07-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0007_moves_movesbylevel_pokemon_moves_by_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
        migrations.RenameModel(
            old_name='MovesByLevel',
            new_name='MoveByLevel',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='moves_by_level',
            new_name='move_by_level',
        ),
    ]
